# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: uldis sturms blog
email: uldis.sturms@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  uldis sturms blog - anything tech
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uldissturms.github.io" # the base hostname & protocol for your site
twitter_username: uldissturms
github_username:  uldissturms
linkedin_username:  uldissturms

# Build settings
markdown: kramdown
permalink: pretty

analytics:
  provider: google
  google:
    tracking_id: 'UA-35819954-3'

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
